import type { CollectionConfig } from 'payload';

export const BrandStrategies: CollectionConfig = {
  slug: 'brand-strategies',
  admin: {
    useAsTitle: 'strategy_id',
    defaultColumns: ['strategy_id', 'client_id', 'positioning', 'version', 'status'],
  },
  fields: [
    { name: 'strategy_id', type: 'text', required: true, unique: true },
    { name: 'client_id', type: 'text', required: true },
    { name: 'brief_id', type: 'text' },
    { name: 'company_summary', type: 'textarea' },
    { name: 'mission', type: 'textarea' },
    { name: 'vision', type: 'textarea' },
    { name: 'core_values', type: 'json' },
    { name: 'positioning', type: 'textarea' },
    { name: 'unique_selling_prop', type: 'textarea' },
    { name: 'audience_profile', type: 'textarea' },
    { name: 'customer_personas', type: 'json' },
    { name: 'brand_personality', type: 'textarea' },
    { name: 'emotional_positioning', type: 'textarea' },
    { name: 'brand_keywords', type: 'json' },
    { name: 'tone_of_voice', type: 'textarea' },
    { name: 'visual_keywords', type: 'json' },
    { name: 'competitor_gap', type: 'textarea' },
    { name: 'social_media_direction', type: 'textarea' },
    { name: 'strategy_json', type: 'json' },
    { name: 'marketing_strategy_json', type: 'json' },
    { name: 'version', type: 'number', defaultValue: 1 },
    { name: 'parent_strategy_id', type: 'text' },
    { name: 'revision_note', type: 'textarea' },
    { name: 'status', type: 'select', options: ['active', 'superseded'], defaultValue: 'active' },
  ],
  timestamps: true,
};
